### ISSUE TITLE
Product requirements doc

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/ComETT#1]
Document defining initial agreed product requirements

**Comment by richpomfret** [comment]
@PatReynolds to take a look at the priority. Others to then review based on the three projects (FR/FC/FBMD)

**Comment by richpomfret** [comment]
Discussed adding in additional features (e.g. OCR/quality control or checking along with including bleed-through project as part of UniTT).

**Comment by DeniseColbert** [comment]
With @richpomfret for sign-off
