### ISSUE TITLE
Investigate universities that teach Ruby/costs of Interns

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/ComETT#10]
https://www.york.ac.uk/about/departments/support-and-admin/careers/employers/internships/ - as a charity we can apply for the Santander funded (summer only, don't know if summer 2022 will run again) which covers 50% of costs up to £1,500. Typical costs 2021:
12 week part time (20 hrs p/wk)  £2400 
8 week full time (37 hrs p/wk) £2,960

Northumbria University is also Santander funded, https://www.northumbria.ac.uk/business-services/engage-with-us/case-studies-and-partnerships/case-studies/santander-universities/internship-and-placement-programme/ - they have a BSc in Computer Science for Web Development ...

https://careerweb.leeds.ac.uk/info/31/advertise_a_job_or_internship

https://humberinternships.co.uk/ offers a subsidy for 12 week internships.

Which universities teach Ruby???
University of Mancheter (but doesn't seem to have info on internships/placements aimed at employers).

**Comment by DeniseColbert** [comment]
Note to add Sam to this story once on GH

**Comment by richpomfret** [comment]
Sam now added.

**Comment by PatReynolds** [comment]
Denise has sent me handles to tag - will do an #AncestryHour this evening.

**Comment by PatReynolds** [comment]
@PatReynolds to find/ask Ruby community on Twitter, and also look for such a community on other channels.
