### ISSUE TITLE
Change Field Parameters - Error Message - Unable to proceed

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#100]
I selected all bar 2 of the baptism fields to create transcription package. Fields came up in groups. I clicked on &#039;Change Field Parameters&#039; and got 8 coding error messages. I went back and transcribed 1 line and submitted it then tried again, same error message. I am using verify by file setting. Created 2nd package but changed my profile to verify by line and same error message occurs. Unable to do further testing. Can provide image of error messages if wanted.

**Comment by dreams-togo** [comment]
stsccfr said: See #104

**Comment by stsccfr** [comment]
Closing this issue per Bev's comment in #104
