### ISSUE TITLE
Resetting Field Parameters to Default

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#102]
In the Data Entry Fields Manage, if you hit the &#039;reset to default&#039; icon the folling error message comes up

404 - File Not Found
Controller method is not found: enter_parameters_reset

**Comment by DeniseColbert** [comment]
@stsfrcc couldn't reproduce this: he will ask Bev if she still gets this error and if so, steps she took.

**Comment by BevStubbs** [comment]
I can't reproduce the error either now. I think when Hilary remodelled the field parameters, this issue was solved. I changed a field group on one field. Hit the gear icon to save and then hit the reset button and it did so with no problems. This issue can now be closed

**Comment by stsccfr** [comment]
Closing since neither Bev nor Dale can reproduce
