### ISSUE TITLE
Issue #103

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#105]
After resetting the &#039;Notes&#039; field to group 2, I found that the rest of the fields now wrap down the left side of the screen at their proper size. I would suggest that an easier solution for the transcriber is that on the fields selector screen you have an option for grouped fields or not grouped fields. Grouped could stay as it is. Non grouped are set to span the full size of the screen wrapped sequentially on multiple lines. Changing all fields to group 1 is extremely time consuming.  

Reported as a bug but also enhancement and user experience

**Comment by stsccfr** [comment]
There is no issue #133 and I think #103 was meant

**Comment by DeniseColbert** [comment]
This is a comment for #103 which is closed so closing this too.
