### ISSUE TITLE
Evaluate potential of LinBMD

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/ComETT#12]
LinBMD, created by Richard Higgs, is at https://github.com/andrew-m-higgs/linBMD

**Comment by richpomfret** [comment]
Shall take a look and see if I can get this running. Shall also investigate the in-development web version that Barrie mentioned.

**Comment by Irene-ene** [comment]
@Irene-ene to send an email to Rich to ask if he got Linux and if he could help
