### ISSUE TITLE
Cannot transcribe marriage records

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#142]
Upon trying to submit a marriage record, I get the error &quot;BaptismDate cannot be blank. Enter ? to force blank.&quot;

**Comment by dreams-togo** [comment]
stsccfr said: This same bug affects all 3 event types, preventing anything from being transcribed. Marriages reference baptism dates, and baptisms and burials both reference marriage dates.

**Comment by stsccfr** [comment]
Hilary said he has fixed this and indeed I cannot reproduce it now, so closing.
