### ISSUE TITLE
Screens from WinREG

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/ComETT#18]
It would be very helpful for us to put together a document with screenshots from Winreg, demonstrating the 'flow', features and UI. We can then use this to show our new designers what we need/basis for any re-design/update.

**Comment by richpomfret** [comment]
@richpomfret to send Kathryn links to transcription software to get a feel for the way they work/look (Zooniverse, CSI and Ben's software).

**Comment by PatReynolds** [comment]
@PatReynolds to send the links

**Comment by PatReynolds** [comment]
More here: https://docs.google.com/spreadsheets/d/1Bhw4RpjpIfSsbDhbegm66fMOxdE-cghSs8UHaE35A9s/edit?pli=1#gid=0

Sent links to Kathryn 26/7/2022
