### ISSUE TITLE
Review alternative online transcription software

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/ComETT#19]
Such as CSI. Assess/evaluate and see what we might include in ours.

**Comment by DeniseColbert** [comment]
@PatReynolds to send links from Ben to Eric/Steve to trial.

**Comment by PatReynolds** [comment]
Reviews are here: https://docs.google.com/document/d/1POfTMIYizS2Mu4st2Y0Uw9gFGRSGtyRRV2wMkpeyp3c/edit?usp=sharing link opens for FreeUKgenealogy addresses - please let me know if you need access with a different address
