### ISSUE TITLE
Technical Plan (specification doc)

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/ComETT#2]
Technical specification/architecture plan - follows the high-level product requirements plan, stating current plan for building the project e.g. RoR using multimodal codebase and feasibility.

**Comment by Irene-ene** [comment]
@PatReynolds to forward Project Plan to @Irene-ene

**Comment by DeniseColbert** [comment]
@Irene-ene to follow up with @richpomfret

**Comment by PatReynolds** [comment]
@DeniseColbert to resend email to Pat

**Comment by richpomfret** [comment]
Would be good for @Vino-S to look over this when she can and provide rough guesstimates on sizes for each task/epic
