### ISSUE TITLE
Research open source online spreadsheet code

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/ComETT#25]
To research what open source code might be out there for online spreadsheets which we may use.

**Comment by benwbrum** [comment]
The library we used for FromThePage is [HandsOnTable](https://handsontable.com/).  They are [no longer free software](https://handsontable.com/blog/articles/2019/3/handsontable-drops-open-source-for-a-non-commercial-license), so we weren't able to incorporate the current version into our AGPL 3.0-licensed tool, but the releases 6.2.2 and earlier (and probably some forks of 6.2.2) are licensed under MIT, so can be incorporated into FreeUKGenealogy projects as I understand them.

**Comment by DeniseColbert** [comment]
@richpomfret is this story relating to the Wordpress issue or is it something we need for in-house development?
