### ISSUE TITLE
Find suitable Integrated Development Environment (IDE)

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/ComETT#27]
Set-up is currently a block/bottleneck for getting new coders onboard. To research and experiment with a suitable IDE for Ruby.

E.g. https://www.monocubed.com/blog/best-ruby-on-rails-ide/

**Comment by richardofsussex** [comment]
The current setup instructions require the developer to implement a local copy of the relevant MongoDB resources. It also requires MySQL and MongoDB software. We could finesse these requirements by providing access to a shared "developer" database containing the required resources. This may require protection e.g. by OpenSSH, but Lemon has successfully given me access to MongoDB resources in this way (which I can view using the Community Edition of Studio 3T).

Given that we can expect a RoR developer to have already set up a development framework which works for them, the setup task then becomes one of installing our code base (i.e. the GitHub bit) and connecting to our remote data resources. This assumes that their preferred RoR software will let them fire up a Rails instance driven by our code, so they can see the effect of the code changes they make.

It took me two months in total to get going on RoR development. First time around on a Windows machine, 'bundle install' had been running for a _week_ when my computer decided to do a Windows update and killed it. Eventually I succeeded on a Linux laptop. Can we find a better way of installing all the required gems, etc., than these obscure command-line procedures? I can write something in Inno Setup for Windows, so long as I know what we want to install, and where it should go.

I think that helping developers get set up on their own machines (_easily_) would be preferable to a cloud-based solution, where we have cost implications, shared use issues, etc.

**Comment by richardofsussex** [comment]
Having now implemented a working platform on both Windows and Linux, I would comment further:

- the issue of incompatible versions being pulled in by bundle install remains a problem, especially on Linux (for some reason). If we are going to support a strategy of fixing the version we want developers to use (as we say we are) then maybe the version of _every_ gem file should be specified for bundle install. Conversely, if we want developers to install the current version of each gem file, someone needs to periodically check for newly-deprecated resources and new incompatibilities, given that the world from which we are pulling these resources is not static
- I have found Rubymine to be very helpful, both for setting up a development framework and for working with the code once it is set up. I have it running on both Windows and Linux. It is modestly priced, and we could offer a licence to developers as a benefit for getting involved
