### ISSUE TITLE
Project Plan doc

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/ComETT#3]
After the high level requirements doc and technical plan are in place, the project plan can be put together as part of the feasibility/preplanning phase. The project plan provides a rough outline to delivery and may include details on resources, risk analysis, timebox/sprint plan and iteration/release plan.

**Comment by DeniseColbert** [comment]
@Irene-ene to follow up with @richpomfret

**Comment by richpomfret** [comment]
High level plan sent through to Iryna/Pat. To be updated at the end of every sprint or every other sprint (at least every Release).
