### ISSUE TITLE
Project = FreeREG. Environment = TEST. UserID = freeregdev. Subject = Fetch issues from github and show in table - allow search

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#47]
We can already create an github issue in FreeComETT. 
But we cannot see them without logging on to github
Create a function in FreeComETT to fetch all open FreeComETT issues and show them in a table. Allow search of table.
See here https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#list-repository-issues

**Comment by DeniseColbert** [comment]
Done, closing
