### ISSUE TITLE
Copy and Paste

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#55]
Should be enabled for all fields but especially the date field. Having to type the month and year is really frustrating. I copy the month and the year and then I only have to type the day. It really speeds up the transcription

**Comment by DeniseColbert** [comment]
Already available for all fields by using the INSERT button. Make testers (also transcribers when live) aware of shortcuts

**Comment by DeniseColbert** [comment]
Dale reports that shortcuts don't work for him, and will find out if this is the same for other testers too.

**Comment by dreams-togo** [comment]
stsccfr said: Bev told me that the shortcuts are not working for her either, so I filed issue #117 as a bug.

**Comment by DeniseColbert** [comment]
Superseded so closing
