### ISSUE TITLE
Logging in more than once

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#68]
The system lets me log in to Freecomett on one tab, start working, then open another tab and log in again. When I then try and select the &quot;Transcribe &quot; action on the second tab (already selected on first tab), click Go, I get an exception error. I then go Back, select again and it works ok.
Do you want users to be able to log in twice on the same device? Would it be better to show &quot;already logged on&quot; type message? I can&#039;t see how to paste an image of the exception screen here. It was &quot;Undefined variable $last_line_key&quot;

**Comment by DeniseColbert** [comment]
Shouldn't be a problem going forward.
