### ISSUE TITLE
Ability to add fields part way through a transcription or to hide or unhide fields as with WinREG

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#77]
This would mean the transciber could select all available fields and hide the ones where there may only be a few entries that apply. It would enable much faster tabbing through the fields and cover an unanticipated field showing up on say one record. This was available on WinReg.

**Comment by DeniseColbert** [comment]
@dreams-togo implemented a button above history table to manage fields: closing
