### ISSUE TITLE
Recruit tech volunteers

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/ComETT#8]
We will require 1-2 tech volunteers to help build this project.

**Comment by Irene-ene** [comment]
Contacted 5 people. Wait for answer

**Comment by richpomfret** [comment]
Check on those who already have experience with RoR and for those who do not, ensure they plan to volunteer with us for a decent length of time.

**Comment by richpomfret** [comment]
We have one now onboarding with Vino - to review and see if we can have another also.

**Comment by richpomfret** [comment]
Looking at IDE's to help reduce friction in getting volunteers set-up. @Vino-S to take a look and @PatReynolds to investigate Cloud9 on AWS with @lemon-ukgen

**Comment by PatReynolds** [comment]
@PatReynolds to check what Charity digital has on offer, and follow up with Lemon.

**Comment by PatReynolds** [comment]
Charity Digital doesn't have an IDE.  Hetzner do not offer an IDE as a service.  Lemon asked for costings.

**Comment by Irene-ene** [comment]
Ask Rich who to contact, Ruby or PHP people?

**Comment by richpomfret** [comment]
Ruby for now.
