### ISSUE TITLE
Fields Selection Page - Add a &#039;tick all fields&#039; selection box

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#89]
At present we can&#039;t add a field after creating the transcription package. My short term solution is to add all the fields. As I can&#039;t hide the fields it means a lot of tabbing but preferable to getting halfway down a page and finding addional info that we have a flexible csv. field for. At the moment I can&#039;t find a way to deselect images from the package (or if you can -  how to do it) to do a new one with the extra field.  This is exemplified by one of the test marriages which actually had a mother&#039;s name rather than a father&#039;s. Very rare on CofE registers but it does happen. 

Thanks

**Comment by DeniseColbert** [comment]
Done, closing
