### ISSUE TITLE
How to get back to previous image

### ISSUE THREAD

**Issue by dreams-togo** [FreeUKGen/ComETT#93]
I moved to the next image in the package before completing the first image but now can&#039;t get back. 
How do I do this please?

**Comment by dreams-togo** [comment]
Previous image button added to transcribe page.

**Comment by dreams-togo** [comment]
this is a comment

**Comment by dreams-togo** [comment]
this is a comment

**Comment by dreams-togo** [comment]
this is a comment

**Comment by dreams-togo** [comment]
this is a comment

**Comment by dreams-togo** [comment]
I have tested this and it works

**Comment by dreams-togo** [comment]
freeregdev said: I tested it twice

**Comment by dreams-togo** [comment]
freeregdev said: this is a comment

**Comment by stsccfr** [comment]
Closing this issue, as the Previous Image button has been tested and is working
